### ISSUE TITLE
Feature Request: Play/Stop Button Status Feedback

### ISSUE THREAD

**Issue by tasyne** [scooper4711/obsidian-syrinscape#7]
Thanks for your work on this, I'm greatly enjoying the plugin!

Currently, the play and stop buttons do not reflect the status of currently-playing sounds. I only know a sound is playing because I clicked a button, while some sounds are quiet at the beginning or throughout their length, creating a disconnected UI feeling.
Many other sound player UIs have feedback reflected in their buttons: A single play button becomes a stop button until the sound is done playing, for example.

The Syrinscape API may have the ability to return some kind of state reflecting the state of play in the web player
https://syrinscape.com/online/frontend-api/state/

This feature request is to adjust some component of the UI to reflect the "currently playing" state of an audio (or all audio).

**Comment by scooper4711** [comment]
I think you're going to love what I'm working on. An integrated player. You'll be able to see that something is playing with the visualization effects.

I hear you on the start becomes a stop button. No promises, but I'll see what I can do.

**Comment by tasyne** [comment]
I saw the other Issue where you mentioned an integrated player. That sounds excellent. My current use-case is the Syrinscape local player + Deep Links + Obsidian URLs. It's a pain to copy/paste each URL in, but at least I don't have to use the web player. I'm a big fan of not opening the web player. This plugin sells me on it though, if I have to have another tab open somewhere it's fine.

**Comment by scooper4711** [comment]
The player pops up in the right hand side - similar to e.g. dice tray or initiative tracker. Once it’s running, you can switch to e.g. initiative tracker and not really worry about it. You pull it up only if you want to mute, adjust volume or stop everything.

If you’re interested in testing, I could get you early access if you’d like. This is a big change, and I’m going to want to have  lots of testing.

**Comment by tasyne** [comment]
Sure thing. I'm set up for plugin development already. Do you accept PRs?

**Comment by scooper4711** [comment]
Oh heck yeah!

note that I’ll be changing how things are called (no more restful api once I have the embedded player working)

**Comment by scooper4711** [comment]
@tasyne  - take a look at the branch 'player'. Still some bugs in it - documented in the most recent commit message. But this is the direction I want to take it.

![image](https://github.com/scooper4711/obsidian-syrinscape/assets/1970249/88cbbe0a-1402-43e7-b438-5e5b96883c83)

**Comment by tasyne** [comment]
Oh yeah. That's quick. And now player is merged in. This is pretty great!

**Comment by scooper4711** [comment]
Please test and let me know how you like it.

**Comment by tasyne** [comment]
Looks to work well. I have not seen that "activation" bug you mentioned in the log. I no longer see the page-switching bug with the play/stop buttons not rendering, and requiring a page close/open.
On a separate note, I was looking into hooking the events for determining if a sound was playing, but from the syrinscape website it looks like there are only two or three events, and those are used for large-scale UI changes (mood or switching from fantasy->sci-fi), but the SocketAPI.Server may have some ability to do this. I can break on any given audio "stop" using line 186 in webpack://syrin-player/src/modules-core/syncSystem/syncSystem.ts  so I imagine if each play/stop button was given an ID and that system was hooked, it would be possible to adjust any buttons with that ID to then add/remove a playing icon (🎵). Nice job incorporating the website's own JS to get access to various methods. My VSCode doesn't like the "syrinscape" variable but everything else works nicely with the types put in syrinscape.d.ts
Update: The VSCode thing was solved by restarting the typescript server, nbd.

**Comment by scooper4711** [comment]
If you assigned the button an id that was deterministic, then first time someone puts two of the same e.g. sound effect on the same note or even two notes and split-paged it, you'd have an issue.

Maybe we could add a class - e.g. `mood-123` or `element-234` to each button, and then query the document for all anchor links with a given class.

**Comment by scooper4711** [comment]
@tasyne  - if you want, I've just pushed a branch that addresses this feature request. Please give it a whirl.
